In [242]:
import pandas as pd
import re
from datetime import datetime, date

In [243]:
votes_backup = pd.read_csv("baarbierians_voting_backup.csv")

In [244]:
votes_backup.head()

,filled_by,date,category,winner,in_pub,points,winner_num
0,Andrew,2025-06-06,Captains Performance,Andreas,True,1,1
1,Andrew,2025-06-06,Drama Queen,Bats,False,-2,1
2,Andrew,2025-06-06,Duffer,Hubert,True,-1,1
3,Andrew,2025-06-06,Duffer,Panu,False,-2,2
4,Andrew,2025-06-06,Goal of the Night,Andreas,True,1,1

In [289]:
votes_backup["date"] = pd.to_datetime(votes_backup["date"]).dt.date

In [290]:
last_backup_date = votes_backup["date"].max()
last_backup_date

datetime.date(2025, 6, 6)

In [246]:
chat = open("_chat.txt", "r").read()

In [247]:
messages = chat.split('\n[')

In [248]:
chat_voting = [x for x in messages if "Voting results" in x]

In [250]:
chat_voting = [re.search('(?<=\] ).*', re.sub("\n", ";", x))[0].replace(u"~\u202f", "").replace(u"\u200e<This message was edited>", "").strip() for x in chat_voting]

In [251]:
chat_voting

['Andrew Irvine: Voting results 28.7:;Save of the Night: Didi(1);Goal of the night: Didi (1);Skill moment: Finn(1);Worst tackle: Guy (-1);Duffer: Anar (-2);Golden Goal: Jura (0);Captain‘s Performance: Andy L. (1);Drama Queen: Martial (-2);Greedy Bastard: Peter P (-2);\u200e[28.07.2023, 23:19:08] Gerd Wichmann: Amazing start of the season👍 Nur der HSV \u200eimage omitted;\u200e[29.07.2023, 13:30:13] Anar Habib: \u200eimage omitted',
 'Andrew Irvine: Voting results 4.8:;Save of the Night: Hubert (1);Goal of the night: Hogie 007 (1);Skill moment: Christoph (1);Worst tackle: Ian P (-2);Duffer: Andrew(-1);Golden Goal: Jura (0),  Oscar (0);Captain‘s Performance: Mark B (1);Drama Queen: Jura (-2);Greedy Bastard: Peter P (-2)',
 'Andrew Irvine: Voting results 11.8:;Save of the Night:Rodrigo (1);Goal of the night: Maris(1);Skill moment: Jura (1);Worst tackle: Simon (-2);Duffer: Andrew (-1);Golden Goal: Martial (0);Captain‘s Performance: Scott (1);Drama Queen: Simon(-2);Greedy Bastard: Andy (-2), Simon (-2), Gary (-2), David(-2), Hogie (-2);\u200e[12.08.2023, 14:22:46] Jura Pereira das Neves: \u200eimage omitted',
 'Andrew Irvine: Voting results 18.8:;Save of the Night: Carlo‘s bollocks (1);Goal of the night: Guy (old) (1);Skill moment: Jura (1);Worst tackle: Pier (-1);Duffer: Pat (-2)…and his floppy end;Golden Goal: Young Guy(0);Captain‘s Performance: Simon (1);Drama Queen: Gökhan (-1);Greedy Bastard: Roman V (-2)',
 "Andrew Irvine: Corrected Voting results 18.8:;Save of the Night: Carlo‘s bollocks (1);Goal of the night: Guy (old) (0);Skill moment: Jura (1);Worst tackle: Pier (-2);Duffer: Pat and his floppy end(-2);Golden Goal: Young Guy(0);Captain‘s Performance: Simon (1);Drama Queen: Gökhan (-2);Greedy Bastard: Roman V (-2);\u200e[18.08.2023, 23:36:54] Pat Roby: I'm not supposed to be using this for 8 weeks, but, for tonight's pubgoers I'll make an exception \u200eimage omitted",
 'Andrew Irvine: Voting results 25.8:;Save of the Night: Stijn (1);Goal of the night: Jura(1);Skill moment: Hubert (1);Worst tackle: Pier(-2);Duffer: Andrew(-1);Golden Goal: Simon (1) , Carlo(1);Captain‘s Performance: Stijn (1);Drama Queen: Andy (-2);Greedy Bastard: Panu(-1)',
 'Andrew Irvine: Voting results 8.9:;Save of the Night: André C (0);Goal of the night: Jura (1);Skill moment: Jura (1);Worst tackle: Dave Mckimm(-2)….some things never change;Duffer: Mark B(-2);Golden Goal: Pier (0);Captain‘s Performance: Scott (1);Drama Queen: Giovanni (-2), André (-2);Greedy Bastard: Finn(-2)',
 'Andrew Irvine: Voting results 15.9:;Save of the Night: Olivier (1);Goal of the night: Jura (1);Skill moment: Daniel B. (0);Worst tackle: Stijn(-2);Duffer: Nick (-2);Golden Goal: Sam P (0);Captain‘s Performance: Jura (1);Drama Queen:Stijn (-2) & Neil (-2);Greedy Bastard: Giovanni (-1)',
 'Andrew Irvine: Voting results 22.9:;Save of the Night: Christoph (1);Goal of the night: Renan (0);Skill moment: Daniel (1);Worst tackle: Daniel (-1);Duffer: Maris (-2);Golden Goal: Giovanni (0);Captain‘s Performance: Hubert (1);Drama Queen:Mark B (-2);Greedy Bastard: Ferhat (-2)',
 'Andrew Irvine: Voting results 29.9:;Save of the Night: Simon(1);Goal of the night: Didi (1);Skill moment: Andreas (1);Worst tackle: Pier (-2);Duffer: Andrew (-1);Golden Goal: Finn(1);Captain‘s Performance: Andreas (1);Drama Queen: Mark B (-1);Greedy Bastard: Tamas(-2)',
 'Andrew Irvine: Voting results 6.10:;Save of the Night: Hubert (1);Goal of the night: Finn (1);Skill moment: Peter R (1);Worst tackle: Simon (-1);Duffer: Gerd (-1) & Alistair (-1);Golden Goal: Dan W (0);Captain‘s Performance: Scott (1);Drama Queen: Gerd (-1);Greedy Bastard: Ferhat (-2)',
 'Gary Hibbett: Voting results 13.10:;Save of the Night: Jose (0);Goal of the night: Jura (+1);Skill moment: Mark H (+1);Worst tackle: Manu (-2);Duffer:  Olivier (-2);Golden Goal: ;Captain‘s Performance: ;Drama Queen: Andre C (-2);Greedy Bastard:',
 'Andrew Irvine: Voting results 20.10:;Save of the Night: Finn W (1);Goal of the night: Scott (1);Skill moment: Simon (1);Worst tackle: Maris (-1);Duffer: Andrew (-1);Golden Goal: Jura (1);Captain‘s Performance: Finn W (1);Drama Queen: Finn (-1);Greedy Bastard: André C(-2)',
 'Andrew Irvine: Voting results 27.10:;Save of the Night: Hubert (1);Goal of the night: Chris(0);Skill moment: Giovanni (0);Worst tackle: Maris (-2);Duffer: Simon(-1);Golden Goal: Scott (1);Captain‘s Performance: Hubert (1);Drama Queen: Finn (-1);Greedy Bastard: Giovanni (-2);\u200e[28.10.2023, 08:45:01] Simon Waddington: Left boot missing ,if anybody see a left boot \u200eimage omitted',
 'Andrew Irvine: Voting results 3.11:;Save of the Night: Didi (0);Goal of the night: Gireg (0);Skill moment: Nik (0);Worst tackle:André V (-2);Duffer: Andrew (-1);Golden Goal: André V (0) ;Captain‘s Performance: Finn (1);Drama Queen: Mike F (-2);Greedy Bastard: Pier (-2)',
 'Scott: Voting results 10.11:;;Save of the Night: Guy (0);Goal of the night: Mark B (0);Skill moment: Emilio (0);Worst tackle: Sam P (-2);Duffer: Andy (-1);Drama Queen: Pier (-2);Greedy Bastard: Pier (-2);Golden Goal: Sam P (0);Captain‘s Performance: Mark H (1)',
 'Andrew Irvine: Voting results 17.11:;Save of the Night: Hogie (1);Goal of the night: Gökhan (0);Skill moment: Simon(1);Worst tackle: Hogie (-1);Duffer:  Andrew (-1);Golden Goal: Jura(1);Captain‘s Performance: Andy the younger (1);Drama Queen: Gökhan (-2);Greedy Bastard: Gökhan (-2)',
 'Andrew Irvine: Voting results 24.11:;Save of the Night: Bonner (1);Goal of the night: Stijn (1);Skill moment: Andy the younger (1);Worst tackle: Pat (-2);Duffer:  Andrew (-1);Golden Goal: Scott(0);Captain‘s Performance: Christoph (1);Drama Queen: Finn (-1);Greedy Bastard: Jack (-1)',
 'Scott: Voting results 01.12:;Save of the Night: Finn (0);Goal of the Night: Hubert (1);Skill moment: Neil H (0);Worst tackle: Bonner (-2);Duffer: Mark H (-1);Golden Goal: Gokhan (0);Captain‘s Performance: Gary (1);Drama Queen: Martial, Pier, Mike F (-2 each);Greedy Bastard: Gokhan (-2)',
 'Andrew Irvine: Voting results 08.12:;Save of the Night: Jack P (0);Goal of the night: James (0);Skill moment: Gary (1);Worst tackle: Gireg (-2);Duffer:  Scott (-1)💪🏻;Golden Goal: Finlay (0);Captain‘s Performance: Scott (1);Drama Queen: Hogie (-1);Greedy Bastard: Simon (-1)',
 'Andrew Irvine: Voting results 15.12:;Save of the Night: Harald (1);Goal of the night: Guy L (0);Skill moment: Daniel (1);Worst tackle: Jura (-1);Duffer:  Scott (-1);Golden Goal: Guy L(0);Captain‘s Performance: Daniel (1);Drama Queen: Panu (-1);Greedy Bastard: Andrew (-1)',
 'Andrew Irvine: Voting results 12.1:;Save of the Night: Didi (1);Goal of the night: Simon (1);Skill moment: Simon(1);Worst tackle: Andrew (-1);Duffer:  Mike (-1);Golden Goal: Sam P (0);Captain‘s Performance: Scott (1);Drama Queen: Bonner (-1);Greedy Bastard: Martial (-2)',
 'Gary Hibbett: Voting results 26.1:;Save of the Night: Daniel (0);Goal of the night: Didi (1);Skill moment: Gary (1);Worst tackle: Andre C (-2);Duffer: Sam P (-1);Golden Goal: Finn W (1);Captain‘s Performance: Didi (1);Drama Queen: Guy (-1);Greedy Bastard: Jura (-1)',
 'Andrew Irvine: Voting results 2.2:;Save of the Night: Leigh Q (0);Goal of the night: Jura (1);Skill moment: Giovanni (1);Worst tackle: André V (-2);Duffer: Audi Guy (-2);Golden Goal: Didi(1);Captain‘s Performance: Giovanni (-1);Drama Queen: Didi (-1) 🏊\u200d♂️ ;Greedy Bastard: André C (-2)',
 'Alistair Irvine: Voting results 2.9;Save of the Night: Joren (1);Goal of the night: Jura (1);Skill moment: Simone (1);Worst tackle: Pier (-2);Duffer: Finn (-1) ;Golden Goal: Chris (0);Captain‘s Performance: Jura (1);Drama Queen: Görkan (-2);Greedy Bastard: Pier (-2)',
 'Andrew Irvine: Voting results 16.2:;Save of the Night: Daniel (0);Goal of the night: Leigh Q (0);Skill moment: Andreas (1);Worst tackle: Guy(-1);Duffer: Gerd (-1);Golden Goal: Maris (0);Captain‘s Performance: Finn (1);Drama Queen: Gökhan (-2);Greedy Bastard: Mark B (-2)',
 'Andrew Irvine: Voting results 23.2:;Save of the Night: Hogie (1);Goal of the night: André C (0);Skill moment: Finn(1);Worst tackle: Hogie (-1);Duffer: Gireg (-2);Golden Goal: Finn (1);Captain‘s Performance: Scott (1);Drama Queen: Scott (-1);Greedy Bastard: Finn(-1)',
 'Andrew Irvine: Voting results 1.3:;Save of the Night: Didi (1) ;Goal of the night: Gireg (0);Skill moment: Andrew (1);Worst tackle: Daniel (0);Duffer: Damian (-1);Golden Goal: Scott (1);Captain‘s Performance: Andrew (1);Drama Queen: Pier(-2);Greedy Bastard: Olivier (-1)',
 'Andrew Irvine: Voting results 1.3:;Save of the Night: Didi (1) ;Goal of the night: Gireg (0);Skill moment: Andrew (1);Worst tackle: Daniel (-2);Duffer: Damian (-1);Golden Goal: Scott (1);Captain‘s Performance: Andrew (1);Drama Queen: Pier(-2);Greedy Bastard: Olivier (-1)',
 'Andrew Irvine: Voting results 8.3:;Save of the Night: Didi(0);Goal of the night: Andrew (1);Skill moment: Scott(1);Worst tackle: Pier (-2);Duffer: Andrew (-1);Golden Goal: Mark B (0);Captain‘s Performance: Scott (1);Drama Queen: Daniel (-2);Greedy Bastard: Taller Chris (-2)',
 'Andrew Irvine: Voting results 15.3:;Save of the Night: Gireg (1);Goal of the night: Leigh (0);Skill moment: Gary (1);Worst tackle: Simon (-1);Duffer: Jeremy(-1);Golden Goal: Jura (1);Captain‘s Performance: Mike F(1);Drama Queen: Mike F(-1);Greedy Bastard: The Guy (-2), The nephew(-2)',
 'Andrew Irvine: Voting results 22.3:;Save of the Night: Finn(1);Goal of the night: Dan (0);Skill moment: Paul (1);Worst tackle: Mike F(-2);Duffer: Finn(-1);Golden Goal: Rodrigo(1);Captain‘s Performance: Paul L(1);Drama Queen: Mike F (-2);Greedy Bastard: Finn(-1)',
 'Scott: Voting results:;Goal of the night: Scott (1);Save of the night: Maris (0);Skill moment: Hubert (1);Worst tackle: The ball (-2) (on Maris’s jaw);Duffer: Chris (-2);Golden goal: Maris (0);Captains performance: Akos (1);Drama queen: Andre C (-2);Greedy Bastard: Giovanni (-2)',
 'Andrew Irvine: Voting results 19.4:;Save of the Night: Sam P (0);Goal of the night: Hubert (1);Skill moment: Phil the Cat (1);Worst tackle: Scott(-1);Duffer: Scott(-1);Golden Goal: Gireg (1);Captain‘s Performance: Mike F(1);Drama Queen: Giovanni(-2);Greedy Bastard: Scott(-1)',
 'Andrew Irvine: Voting results 26.4:;Save of the Night: Bonner (1);Goal of the night: Guy (1);Skill moment: Gökhan (0);Worst tackle: Lanky Chris(-2);Duffer: The other Audi guy (-2);Golden Goal: Scott (1);Captain‘s Performance: Hubert (1);Drama Queen: MARK B (-2);Greedy Bastard: Finn (-1)',
 'Scott: Voting results 03.05:;Save of the Night: Jeremy (1);Goal of the night: Akos (1);Skill moment: Lanky Chris (0);Worst tackle: Pier (-2);Duffer: Finn (-1);Golden Goal: Scott (1), Andre V (0);Captain‘s Performance: Akos (1);Drama Queen: Jeremy (-1);Greedy Bastard: Giovanni (-1, but 4 nominations)',
 'Andrew Irvine: Voting results 10.5:;Save of the Night: Daniel (0);Goal of the night: Jura (1);Skill moment: Gary(1);Worst tackle: Bonner (-2);Duffer: Alistair (-2);Golden Goal: Giovanni (1);Captain‘s Performance: Jura(1);Drama Queen: Finn(-2);Greedy Bastard: Giovanni (-1)',
 'Scott: Voting results 17.05:;Save of the Night: Daniel (0);Goal of the Night: Scott (1);Skill moment: New André C (1);Worst tackle: Jura (-1);Duffer: Alistair (-2);Golden Goal: Daniel (0);Captain‘s Performance: Scott (1);Drama Queen: Pier (-2);Greedy Bastard: Pier (-2)',
 'Finn: Voting ;;Voting results 24.05:;Save of the Night: Daniel +1;Goal of the Night: Gio +1 ;Skill moment: Guy +1;Worst tackle: Gio -1 ;Duffer: Mark -1 ;Golden Goal: Akos 0 ;Captain‘s Performance: Daniel +1;Drama Queen: Chris -1;Greedy Bastard: Gio -1',
 'Andrew Irvine: Voting results 31.5:;Save of the Night: Daniel (0);Goal of the night: Stevie(0);Skill moment: Niall(0);Worst tackle: Andy (-2);Duffer: Pier (-2);Golden Goal: Dan W(0);Captain‘s Performance: Scott (1)….by default;Drama Queen: Scott(-1);Greedy Bastard: Scott(-1)',
 'Scott: Voting results Steinhausen Grümpi 7.6.:;Save of the Night: Stijn (1);Goal of the Night: Finn (1);Skill moment: Stijn (1) ;Worst tackle: The nice referee (-2);Duffer: Jura (-2);Golden Goal: Jura (0);Captain‘s Performance: Stijn (1);Drama Queen: Martial (-1);Greedy Bastard: Finn (-1);\u200e[07.06.2024, 22:44:20] Martial Gachet: Victorious penalty \u200evideo omitted',
 "Scott: Voting results 28.6:;Save of the Night: Hubert (1);Goal of the Night: Maris (0) (for the Latvian Hattrick);Skill moment: Simon (1);Worst tackle: Chris (-2);Duffer: Maris (-2);Golden Goal: Alexandru (0);Captain‘s Performance: Hubert (1);Drama Queen: Chris (-2);Greedy Bastard: Finn W (-2) ;\u200e[28.06.2024, 22:16:24] Gary Hibbett: Congratulations to Hubert, unveiled tonight as Baarbierians' new number 81 and formally initiated as a club member. He wants to he a Baarbierian because... \u200eimage omitted",
 'Scott: Voting results Hausen a.A. Grümpi 29.6.:;Save of the Day: Hubert (1);Goal of the Day: Andreas (1);Skill moment: Finlay (1);Worst tackle: Jura (-1);Duffer: Hubert (-1);Golden Goal: Jura (1);Captain‘s Performance: Hubert (1);Drama Queen: Chris (-2);Greedy Bastard: Giovanni (-1)',
 "Scott: Voting results 05.07.2024:;;Goal of the Night: Giovanni (1);Save of the Night: Hubert (1);Skill Moment: Giovanni (1);Worst Tackle: Hubert (-1);Duffer: Maris (-2);Drama Queen: Giovanni (-1);Greedy Bastard: Giovanni (-1);Golden Goal: Simone (0);Captain's Performance: Scott (1)",
 "Andrew Irvine: Voting results 12.07.2024:;;Goal of the Night: Vitor (0);Save of the Night: Scott (1);Skill Moment: Jura (1);Worst Tackle: Scott (-1);Duffer: Martial (-2);Drama Queen: Harald (-2);Greedy Bastard: Finn (-2);Golden Goal: Emilio (0);Captain's Performance: Scott (1)",
 "Scott: Voting results 19.07.2024:;;Goal of the Night: Scott (1);Save of the Night: Hubert (0);Skill Moment: Emilio (0);Worst Tackle: Martial (-2);Duffer: Scott (-1);Drama Queen: Emilio (-2);Greedy Bastard: Didi (-2), Guy L (-2);Golden Goal: Simon (1);Captain's Performance: Maris (1)",
 "Hubert Małek: Voting results 26.07.2024:;;Goal of the Night:  Akos (+1);Save of the Night: Julio (+0);Skill Moment: Daniel (0);Worst Tackle: Finn (-1);Duffer: Akos (-1);Drama Queen: Joren (-2);Greedy Bastard: Joren (-2);Golden Goal: Max (+1);Captain's Performance: Max (+1)",
 "Andrew Irvine: Voting results 02.08.2024:;;Goal of the Night: Max (1);Save of the Night: Daniel (0);Skill Moment: Sam P (0);Worst Tackle: Finn (-1);Duffer: Dino (-2);Drama Queen: Norbert (-1);Greedy Bastard: Pier (-2);Golden Goal: Scott (1);Captain's Performance: Hubert (1)",
 "Scott: Voting results 09.08.2024:;;Goal of the Night: Tall Chris (1);Save of the Night: Short Chris (1);Skill Moment: Oscar H (0);Worst Tackle: Finn (-1);Duffer: Mike F (-1) (4 nominations);Drama Queen: Maris (-1);Greedy Bastard: Giovanni (-2);Golden Goal: Scott (1);Captain's Performance: Short Chris (1);\u200e[09.08.2024, 21:48:10] Mark Buckle: \u200eimage omitted",
 "Scott: Voting results 16.08.2024:;;Goal of the Night: John B (1);Save of the Night: Colin B (1);Skill Moment: Gerd (1);Worst Tackle: John B (-1);Duffer: Mark B (-1);Drama Queen: Gerd (-1);Greedy Bastard: Colin B(-1);Golden Goal: Rollover (Double points next week);Captain's Performance: Cordon Bleu (1)",
 "Alistair Irvine: Voting results 23.08.2024:;;Goal of the Night: Gokhan (0);Save of the Night: Maris (1);Skill Moment: Simon (1);Worst Tackle: Guy L (-2);Duffer: Mike F (-2);Drama Queen: Dan W (-2);Greedy Bastard: Hubert (-1);Golden Goal: Mike F (0);Captain's Performance: Maris (1)",
 "Scott: Voting results 20.09.2024:;;Goal of the Night: Welsh Nick (1);Save of the Night: Jeremy (1);Skill Moment: Guy L (1);Worst Tackle: Lloyd (-1);Duffer: Finn (-1);Drama Queen: Mark Buckle’s stomach (-2);Greedy Bastard: Finn (-1);Golden Goal: Didi (1);Captain's Performance: Scott (1)",
 "Andrew Irvine: Voting results 27.09.2024:;;Goal of the Night: Hubert (1);Save of the Night: Didi (0);Skill Moment: Maris (1);Worst Tackle: Tall Chris (-2);Duffer: Andrew (-1);Drama Queen: Finn (-1);Greedy Bastard: André V (-2);Golden Goal: André V (0);Captain's Performance: Maris (1)",
 "Scott: Voting results 04.10.2024:;;Goal of the Night: Gireg (1);Save of the Night: Scott (1);Skill Moment: Bats (1);Worst Tackle: Bats (-1);Duffer: Finn (-2);Drama Queen: Mark B (-2);Greedy Bastard: André Cecílio (-2);Golden Goal: New Mike (1);Captain's Performance: Bats (1)",
 "Scott: Voting results 11.10.2024:;;Goal of the Night: Finn’s Head (1);Save of the Night: Lloyd (1);Skill Moment: Mike F (0);Worst Tackle: André C (-2), André V (-2);Duffer: Chris Shires (-2);Drama Queen: Sam H (-2);Greedy Bastard: André V (-2);Golden Goal: Chris Shires (0);Captain's Performance: Lloyd (1)",
 "Andrew Irvine: Voting results 18.10.2024:;;Goal of the Night: Hubert (1);Save of the Night: Lloyd (1);Skill Moment: Tall Chris (1);Worst Tackle: Gireg (-2);Duffer: Mark H (-1);Drama Queen: Andrew (-1);Greedy Bastard: Lloyd (-1);Golden Goal: Finn (1);Captain's Performance: Scott (1)",
 "Andrew Irvine: Voting results 08.11.2024:;;Goal of the Night: Akos (1);Save of the Night: Pier (0);Skill Moment: Scott (1);Worst Tackle: Gerd (-1);Duffer: Martin G (-1);Drama Queen: Andrew (-1);Greedy Bastard: Gerd (-2);Golden Goal: Simon (1);Captain's Performance: Simon (1)",
 "Andrew Irvine: Voting results 15.11.2024:;;Goal of the Night: Mark B (0);Save of the Night: Crossbar (0);Skill Moment: Andreas (1);Worst Tackle: Mark B (-2);Duffer: Gary (-1);Drama Queen: Guy L (-1);Greedy Bastard: Guy L (-1);Golden Goal: Andreas (1);Captain's Performance: Guy L (1)",
 "Scott: Voting results 22.11.2024:;;Goal of the Night: Gary (1);Save of the Night: Lanky Chris (1);Skill Moment: Leigh Q (1);Worst Tackle: Bats (-2);Duffer: Simon (-1);Drama Queen: Finn (-2);Greedy Bastard: Mark B (-2);Golden Goal: Jayden (0);Captain's Performance: Leigh Q (1);\u200e[22.11.2024, 22:58:54] Gary Hibbett: Level of our game was raised tonight... \u200eimage omitted",
 "Scott: Voting results 29.11.2024:;;Goal of the Night: Maris (1);Save of the Night: Lloyd (1);Skill Moment: Mark B (1);Worst Tackle: Leigh’s laces (-1);Duffer: Adam M (-1);Drama Queen: Finn (-2);Greedy Bastard: Scott (-1);Golden Goal: Emilio (0);Captain's Performance: Lloyd (1)",
 "Scott: Voting results 06.12.2024:;;Goal of the Night: Francisco (1);Save of the Night: Julio (0);Skill Moment: André C (0);Worst Tackle: John B’s wife (-2);Duffer: Simon (-1);Drama Queen: Niall (-2);Greedy Bastard: Damian (-2);Golden Goal: Jack P (0);Captain's Performance: Francisco (1)",
 "Scott: Voting results 13.12.2024:;;Goal of the Night: Mark B (1);Save of the Night: Mark H (1);Skill Moment: Uncle Bats (0);Worst Tackle: Daniel (-2);Duffer: Simon (-1);Drama Queen: Bats (-2);Greedy Bastard: Finn (-2);Golden Goal: Martial (0);Captain's Performance: Mark B (1)",
 "Scott: Voting results 20.12.2024:;;Goal (Winning Shot) of the Night: Gireg (1);Save of the Night: Andy K (1), Scott (1);Skill Moment: Maris (1);Worst Tackle: Gireg (-1);Duffer: Maris (-1);Drama Queen: Andy K (-1);Greedy Bastard: Simon (-1);Golden Goal (Last winning shot): Martial (1);Captain's Performance: Maris (1)",
 "Andrew Irvine: Voting results 27.12.2024:;;Goal of the Night: Alistair (1);Save of the Night: Mark H (1);Skill Moment: Maris (1);Worst Tackle: Simon (-1);Duffer: Andrew (-1);Drama Queen: Finn (-2);Greedy Bastard: Neil H (-2), Finlay (-2), Sam H (-2), Connor H (-2);Golden Goal: Connor H (0);Captain's Performance: Alistair (1)",
 "Andrew Irvine: Voting results 03.01.2025:;;Goal of the Night: Scott (1);Save of the Night: Alistair (1);Skill Moment: New Mike (0);Worst Tackle: Oscar H (-2);Duffer: Steve S (-2)…. 🚗 💥 ;Drama Queen: Mark B (-2);Greedy Bastard: Carlo (-1);Golden Goal: Rodrigo (0);Captain's Performance: Hubert (1)",
 "Scott: Voting results 10.01.2025:;;Goal of the Night: Jack P (1);Save of the Night: Mark B (0);Skill Moment: Pat (0);Worst Tackle: Maris (-1);Duffer: Mark B (-2);Drama Queen: Maris (-1);Greedy Bastard: André V (-2);Golden Goal: Tilo (0);Captain's Performance: Jack P (1)",

In [252]:
chat_voting = [x for x in chat_voting if re.search('(?<=Voting results )\d{2}.\d{2}.\d{4}', x) and not x.startswith("Chris")]

In [253]:
CATEGORIES = {"Goal of the Night": True,
            "Save of the Night": True,
            "Skill Moment": True,
            "Worst Tackle": False,
            "Duffer": False,
            "Drama Queen": False,
            "Greedy Bastard": False,
            "Golden Goal": True,
            "Captain's Performance": True}

In [254]:
chat_votes = [
    {
        "filled_by" : re.search('[A-Za-z]+(?=[- :])', x)[0],
        "date" : datetime.strptime(re.search('(?<=Voting results )\d{2}.\d{2}.\d{4}', x)[0], "%d.%m.%Y").date(),
        "category": category,
        "winner": (
            (re.search(f"(?<={category}:)[^;]+", x)[0])
            .strip()
            .replace("&", ",")
            .replace("The Americans (John B (1), Chris Davis (1))", "John B (1), Chris Davis (1)")
            .replace("The whole Wichmann family (-1/-2)", "Finn W (-1), Gerd W (-1), Gerd's wife (-2)")
            .split(","))
    }
    for x in chat_voting
    for category in CATEGORIES.keys()
    if datetime.strptime(re.search('(?<=Voting results )\d{2}.\d{2}.\d{4}', x)[0], "%d.%m.%Y").date() > last_backup_date
]

In [255]:
chat_votes[:2]

[{'filled_by': 'Andrew',
  'date': datetime.date(2025, 6, 20),
  'category': 'Goal of the Night',
  'winner': ['Hubert (1)']},
 {'filled_by': 'Andrew',
  'date': datetime.date(2025, 6, 20),
  'category': 'Save of the Night',
  'winner': ['Maris (0)']}]

In [310]:
chat_votes_df = pd.DataFrame(chat_votes).explode("winner")

In [311]:
chat_votes_df

    filled_by        date               category         winner
0      Andrew  2025-06-20      Goal of the Night     Hubert (1)
1      Andrew  2025-06-20      Save of the Night      Maris (0)
2      Andrew  2025-06-20           Skill Moment  Alexandru (0)
3      Andrew  2025-06-20           Worst Tackle    Finn W (-2)
4      Andrew  2025-06-20                 Duffer  Alistair (-1)
..        ...         ...                    ...            ...
409    Andrew  2026-07-24                 Duffer  Not Mike (-2)
410    Andrew  2026-07-24            Drama Queen   Alistair(-1)
411    Andrew  2026-07-24         Greedy Bastard     Stevie(-2)
412    Andrew  2026-07-24            Golden Goal       Tilo (0)
413    Andrew  2026-07-24  Captain's Performance      Leigh (1)

[441 rows x 4 columns]

In [378]:
chat_votes_df["filled_by"] = chat_votes_df["filled_by"].replace("Giovanni", "Gio").replace("Jack", "Jack P")

In [313]:
chat_votes_df.loc[~chat_votes_df["winner"].str.contains(".+\(.+\)"), "winner"] = chat_votes_df.loc[~chat_votes_df["winner"].str.contains(".+\(.+\)"), "winner"] + " (-1)"

In [314]:
chat_votes_df['winner'] = chat_votes_df["winner"].str.replace("( - draw in voting)|(\(new Chris nickname\))|(\(definitely not Mike F\))", "", regex=True)

In [315]:
chat_votes_df["points"] = chat_votes_df["winner"].map(lambda x: int(re.search("(?<=\().+(?=\))", x)[0]))

In [316]:
chat_votes_df["points"].drop_duplicates()

0    1
1    0
3   -2
4   -1
Name: points, dtype: int64

In [317]:
chat_votes_df["in_pub"] = chat_votes_df["points"].abs().eq(1)

In [318]:
chat_votes_df["winner"] = chat_votes_df["winner"].str.replace("\([-\+]?\d\)","", regex=True).str.strip()

In [319]:
chat_votes_df["winner_num"] = chat_votes_df.index.to_series().groupby(level=0).cumcount() + 1

In [345]:
tour_votes1 = pd.DataFrame([
    {
        "category": "Goal of the Night",
        "winner": "Gio",
        "points": 1
    },
    {
        "category": "Save of the Night",
        "winner": "Hubert",
        "points": 1
    },
    {
        "category": "Skill Moment",
        "winner": "Mama Gio",
        "points": 0
    },
    {
        "category": "Worst tackle",
        "winner": "Simon",
        "points": -1
    },
    {
        "category": "Duffer",
        "winner": "Mark B",
        "points": -1
    },
    {
        "category": "Drama Queen",
        "winner": "Gerd W",
        "points": -1
    },
    {
        "category": "Greedy Bastard",
        "winner": "Gio",
        "points": -1
    },
    {
        "category": "Golden Goal",
        "winner": "Lloyd",
        "points": 1
    },
    {
        "category": "Captain's Performance",
        "winner": "Scott",
        "points": 1
    },
])
tour_votes1["date"] = date.fromisoformat("2025-09-12")

In [346]:
tour_votes2 = pd.DataFrame([
    {
        "category": "Goal of the Night",
        "winner": "Francesco",
        "points": 1
    },
    {
        "category": "Save of the Night",
        "winner": "Mark B",
        "points": 1
    },
    {
        "category": "Skill Moment",
        "winner": "Salvio",
        "points": 1
    },
    {
        "category": "Worst tackle",
        "winner": "Gokhan",
        "points": -1
    },
    {
        "category": "Duffer",
        "winner": "Andrew",
        "points": -1
    },
    {
        "category": "Drama Queen",
        "winner": "Lloyd",
        "points": -1
    },
    {
        "category": "Greedy Bastard",
        "winner": "Gio",
        "points": -1
    },
    {
        "category": "Golden Goal",
        "winner": "Jura",
        "points": 1
    },
    {
        "category": "Captain's Performance",
        "winner": "Jura",
        "points": 1
    },
])
tour_votes2["date"] = date.fromisoformat("2025-09-13")

In [347]:
tour_votes = pd.concat([tour_votes1, tour_votes2])
tour_votes["filled_by"] = "Andrew"
tour_votes["winner_num"] = 1
tour_votes["in_pub"] = tour_votes["points"].abs().eq(1)

In [348]:
tour_votes

,category,winner,points,date,filled_by,winner_num,in_pub
0,Goal of the Night,Gio,1,2025-09-12,Andrew,1,True
1,Save of the Night,Hubert,1,2025-09-12,Andrew,1,True
2,Skill Moment,Mama Gio,0,2025-09-12,Andrew,1,False
3,Worst tackle,Simon,-1,2025-09-12,Andrew,1,True
4,Duffer,Mark B,-1,2025-09-12,Andrew,1,True
5,Drama Queen,Gerd W,-1,2025-09-12,Andrew,1,True
6,Greedy Bastard,Gio,-1,2025-09-12,Andrew,1,True
7,Golden Goal,Lloyd,1,2025-09-12,Andrew,1,True
8,Captain's Performance,Scott,1,2025-09-12,Andrew,1,True
0,Goal of the Night,Francesco,1,2025-09-13,Andrew,1,True
1,Save of the Night,Mark B,1,2025-09-13,Andrew,1,True
2,Skill Moment,Salvio,1,2025-09-13,Andrew,1,True
3,Worst tackle,Gokhan,-1,2025-09-13,Andrew,1,True
4,Duffer,Andrew,-1,2025-09-13,Andrew,1,True
5,Drama Queen,Lloyd,-1,2025-09-13,Andrew,1,True
6,Greedy Bastard,Gio,-1,2025-09-13,Andrew,1,True
7,Golden Goal,Jura,1,2025-09-13,Andrew,1,True
8,Captain's Performance,Jura,1,2025-09-13,Andrew,1,True

In [379]:
votes = pd.concat([votes_backup, chat_votes_df, tour_votes])

In [390]:
votes[['points', "winner_num"]] = votes[['points', "winner_num"]].map(int)
votes['in_pub'] = votes['in_pub'].map(str)

In [381]:
votes["winner"].drop_duplicates().sort_values().to_list()

['Abdel',
 'Abduhla',
 'Adam - other',
 'Adam M',
 'Aidan',
 'Akos',
 'Akos’s kid',
 'Akos’s wife',
 'Alejandro',
 'Alexandru',
 'Alfredo',
 'Ali',
 'Ali jee',
 'Alistair',
 'American Chris',
 'Anar',
 'Andis',
 'Andre',
 'Andre V  you left too early',
 'Andreas',
 'Andrew',
 'Andrew - other',
 'Andrew Beatie',
 'Andrew Dickmann',
 'Andrew S',
 'André C',
 'André Cecílio',
 'André V',
 'Andy',
 'Andy (younger)',
 'Andy K',
 "Andy's boyfriend",
 "Andy's mum",
 'Anton',
 'Audi Guy',
 'Bats',
 'Bats’ Uncle',
 'Bert',
 'Brauerei',
 'Captain Tom',
 'Carlo',
 'Carlo’s six pack',
 'Chris Davis',
 'Chris S',
 'Chris Shires',
 'Christian',
 'Christoph',
 'Colin B',
 'Connor',
 'Connor H',
 'Constantijn',
 'Cordon Bleu',
 'Corona virus',
 'Crossbar',
 'Cédric',
 'Damian',
 'Dan W',
 'Dan Y',
 'Daniel',
 'Dave McKimm',
 'Davis',
 'Didi',
 'Didier C',
 'Dino',
 'Dow Maris',
 'Edi',
 'Emilio',
 'Emily Ramsey',
 'Emma Mason',
 'Fat Leigh',
 'Ferhat',
 'Finlay H',
 'Finn',
 'Finn H',
 'Finn W',
 'Francesco',
 'Francisco',
 'Frank H',
 'Gary',
 'Gary - other',
 'Gary on himself',
 'George',
 'Gerd',
 'Gerd W',
 "Gerd's wife",
 'Gio',
 'Gireg',
 'Gokhan',
 'Guy L',
 'Harald',
 'Helen Irvine',
 'Henry',
 'Hermann',
 'Hubert',
 'Hubert  - for coming to the pub after football',
 'Hubert’s sock',
 'Hunor',
 'Ian M',
 'Ian P',
 'Indian Couple',
 'Isam (Dow)',
 'JCP',
 'JD',
 'Jack',
 'Jack Greaves',
 'Jack P',
 'Jake',
 'James (Aussie)',
 "James (Finlay's friend)",
 'James M',
 'Jaou',
 'Jayden',
 'Jeremy',
 'Jesus',
 'Joachim',
 'Jochen',
 'Joe B',
 'John B',
 'John Bonner',
 'John B’s wife',
 'Joren',
 'Jose',
 'José',
 'Joy Paton',
 'Julie P',
 'Julie Popple',
 'Julio',
 'Jura',
 'Karius',
 'Katja',
 'Kenny',
 'Lanky Chris',
 'Lee',
 'Leigh',
 'Leigh (Skinny)',
 'Leigh Q',
 'Lino',
 'Lloyd',
 'Lloyd 🤕',
 'Luciano',
 'Luis',
 'Luke C',
 'Mama Gio',
 'Man Utd',
 'Manu',
 'Maradona',
 'Maris',
 'Maris‘s Wife',
 'Mark B',
 'Mark B’s wife',
 'Mark H',
 'Mark L',
 'Mark U',
 'Martial',
 'Martin G',
 'Martin the younger',
 'Matt M',
 'Matt Sweeny',
 'Max',
 'Megan Bracewell',
 'Messi',
 'Mifail',
 'Mike',
 'Mike F',
 'Mike Fitz',
 'Mike T',
 'Mènage à trois',
 'NHS',
 'Nabi',
 'Natmir',
 'Neil H',
 'Neil P',
 'New Manu',
 'New Mike',
 'Niall',
 'Niall‘s head',
 'Nick',
 'Nick Halliday',
 'Niels',
 'Niels (slimmer)',
 'Nigel',
 'Niklas',
 'Nim',
 'Norbert',
 'Not Mike',
 'Not Mike (Michal)',
 'Ole',
 'Oliver S',
 'Olivier',
 'Oscar H',
 'Panu',
 'Pat',
 'Paul L',
 'Paul Stringer',
 'Paul V',
 'Paul Y',
 'Perspex glass',
 'Peter (Swiss)',
 'Peter H',
 'Peter P',
 'Peter R',
 'Phil (the Cat)',
 'Pier',
 'Pierce',
 'Pontas',
 'Putin',
 'Ramos',
 'Richard',
 'Robson Green',
 'Rodrigo',
 'Rodriguez',
 'Roman V',
 'Roy Keane',
 'Rupert',
 'Salvio',
 'Sam H',
 'Sam P',
 'Scott',
 'Scott (Aussie)',
 'Scott‘s balls',
 'Sideline Lady',
 'Simeon P',
 'Simon',
 'Simon S',
 "Simon's Dog",
 'Simone',
 'Simone‘s mate',
 'Stefano',
 'Stephan L',
 'Stephane',
 'Steve S',
 'Stevie',
 'Stijn',
 'Stynge',
 'Svein',
 'Swiss Chris',
 'Tamas',
 'Tanja (girl who serves in Pub)',
 'The Ball',
 'The Guy',
 'The Lake',
 'The Nephew',
 'The Nice Referee',
 'The Post',
 'The Pub',
 'The Snow',
 'The Sun',
 'The Swiss Government',
 'The Tree',
 'The left Post',
 'The other team',
 'Tilo',
 'Tom',
 'Toni',
 'Uptight Neighbour',
 'Victor',
 'Viktor',
 'Vitor',
 'Wayne',
 'Welsh Nick',
 'Whoever ate Pat‘s keys',
 'Woman in white dress',
 'Yannick B',
 'Zayan',
 'Zobic']

In [382]:
votes["winner"] = votes["winner"].replace("Carlo's six pack", "Carlo").replace("Chris Davis", "American Chris").replace("Chris Shires", "Chris S").replace("Davis", "American Chris").replace("Fat Leigh", "Leigh Q").replace("Finn", "Finn W").replace("Gerd W", "Gerd").replace("Gary on himself", "Gary").replace("Viktor", "Victor").replace("Vitor", "Victor").replace("Not Mike (Michal)", "Not Mike").replace("Ali jee", "Ali").replace("Andre V  you left too early", "André V").replace("Andre", "André V").replace("Connor", "Connor H").replace("Hubert  - for coming to the pub after football", "Hubert").replace("JCP", "Julio").replace("Julie P", "Julie Popple").replace("Leigh (Skinny)", "Lee (skinny)").replace("Lee", "Lee (skinny)").replace("Lloyd 🤕", "Lloyd").replace("Niall‘s head", "Niall").replace("Nick", "Nik").replace("Scott‘s balls", "Scott").replace("Jack", "Jack P")

In [383]:
votes["winner"].drop_duplicates().sort_values().to_list()

['Abdel',
 'Abduhla',
 'Adam - other',
 'Adam M',
 'Aidan',
 'Akos',
 'Akos’s kid',
 'Akos’s wife',
 'Alejandro',
 'Alexandru',
 'Alfredo',
 'Ali',
 'Alistair',
 'American Chris',
 'Anar',
 'Andis',
 'Andreas',
 'Andrew',
 'Andrew - other',
 'Andrew Beatie',
 'Andrew Dickmann',
 'Andrew S',
 'André C',
 'André Cecílio',
 'André V',
 'Andy',
 'Andy (younger)',
 'Andy K',
 "Andy's boyfriend",
 "Andy's mum",
 'Anton',
 'Audi Guy',
 'Bats',
 'Bats’ Uncle',
 'Bert',
 'Brauerei',
 'Captain Tom',
 'Carlo',
 'Carlo’s six pack',
 'Chris S',
 'Christian',
 'Christoph',
 'Colin B',
 'Connor H',
 'Constantijn',
 'Cordon Bleu',
 'Corona virus',
 'Crossbar',
 'Cédric',
 'Damian',
 'Dan W',
 'Dan Y',
 'Daniel',
 'Dave McKimm',
 'Didi',
 'Didier C',
 'Dino',
 'Dow Maris',
 'Edi',
 'Emilio',
 'Emily Ramsey',
 'Emma Mason',
 'Ferhat',
 'Finlay H',
 'Finn H',
 'Finn W',
 'Francesco',
 'Francisco',
 'Frank H',
 'Gary',
 'Gary - other',
 'George',
 'Gerd',
 "Gerd's wife",
 'Gio',
 'Gireg',
 'Gokhan',
 'Guy L',
 'Harald',
 'Helen Irvine',
 'Henry',
 'Hermann',
 'Hubert',
 'Hubert’s sock',
 'Hunor',
 'Ian M',
 'Ian P',
 'Indian Couple',
 'Isam (Dow)',
 'JD',
 'Jack Greaves',
 'Jack P',
 'Jake',
 'James (Aussie)',
 "James (Finlay's friend)",
 'James M',
 'Jaou',
 'Jayden',
 'Jeremy',
 'Jesus',
 'Joachim',
 'Jochen',
 'Joe B',
 'John B',
 'John Bonner',
 'John B’s wife',
 'Joren',
 'Jose',
 'José',
 'Joy Paton',
 'Julie Popple',
 'Julio',
 'Jura',
 'Karius',
 'Katja',
 'Kenny',
 'Lanky Chris',
 'Lee (skinny)',
 'Leigh',
 'Leigh Q',
 'Lino',
 'Lloyd',
 'Luciano',
 'Luis',
 'Luke C',
 'Mama Gio',
 'Man Utd',
 'Manu',
 'Maradona',
 'Maris',
 'Maris‘s Wife',
 'Mark B',
 'Mark B’s wife',
 'Mark H',
 'Mark L',
 'Mark U',
 'Martial',
 'Martin G',
 'Martin the younger',
 'Matt M',
 'Matt Sweeny',
 'Max',
 'Megan Bracewell',
 'Messi',
 'Mifail',
 'Mike',
 'Mike F',
 'Mike Fitz',
 'Mike T',
 'Mènage à trois',
 'NHS',
 'Nabi',
 'Natmir',
 'Neil H',
 'Neil P',
 'New Manu',
 'New Mike',
 'Niall',
 'Nick Halliday',
 'Niels',
 'Niels (slimmer)',
 'Nigel',
 'Nik',
 'Niklas',
 'Nim',
 'Norbert',
 'Not Mike',
 'Ole',
 'Oliver S',
 'Olivier',
 'Oscar H',
 'Panu',
 'Pat',
 'Paul L',
 'Paul Stringer',
 'Paul V',
 'Paul Y',
 'Perspex glass',
 'Peter (Swiss)',
 'Peter H',
 'Peter P',
 'Peter R',
 'Phil (the Cat)',
 'Pier',
 'Pierce',
 'Pontas',
 'Putin',
 'Ramos',
 'Richard',
 'Robson Green',
 'Rodrigo',
 'Rodriguez',
 'Roman V',
 'Roy Keane',
 'Rupert',
 'Salvio',
 'Sam H',
 'Sam P',
 'Scott',
 'Scott (Aussie)',
 'Sideline Lady',
 'Simeon P',
 'Simon',
 'Simon S',
 "Simon's Dog",
 'Simone',
 'Simone‘s mate',
 'Stefano',
 'Stephan L',
 'Stephane',
 'Steve S',
 'Stevie',
 'Stijn',
 'Stynge',
 'Svein',
 'Swiss Chris',
 'Tamas',
 'Tanja (girl who serves in Pub)',
 'The Ball',
 'The Guy',
 'The Lake',
 'The Nephew',
 'The Nice Referee',
 'The Post',
 'The Pub',
 'The Snow',
 'The Sun',
 'The Swiss Government',
 'The Tree',
 'The left Post',
 'The other team',
 'Tilo',
 'Tom',
 'Toni',
 'Uptight Neighbour',
 'Victor',
 'Wayne',
 'Welsh Nick',
 'Whoever ate Pat‘s keys',
 'Woman in white dress',
 'Yannick B',
 'Zayan',
 'Zobic']

In [384]:
votes = votes.sort_values(["date", "category", "winner"])

In [385]:
votes["date"].drop_duplicates().sort_values()

3866    2014-01-03
3856    2014-01-10
3849    2014-01-17
3842    2014-01-24
3837    2014-01-31
           ...
377     2026-06-26
386     2026-07-03
395     2026-07-10
404     2026-07-17
413     2026-07-24
Name: date, Length: 510, dtype: object

In [387]:
votes["date"].drop_duplicates().sort_values().to_list()

[datetime.date(2014, 1, 3),
 datetime.date(2014, 1, 10),
 datetime.date(2014, 1, 17),
 datetime.date(2014, 1, 24),
 datetime.date(2014, 1, 31),
 datetime.date(2014, 2, 7),
 datetime.date(2014, 2, 14),
 datetime.date(2014, 2, 21),
 datetime.date(2014, 2, 28),
 datetime.date(2014, 3, 7),
 datetime.date(2014, 3, 14),
 datetime.date(2014, 3, 21),
 datetime.date(2014, 3, 28),
 datetime.date(2014, 4, 4),
 datetime.date(2014, 4, 11),
 datetime.date(2014, 4, 25),
 datetime.date(2014, 5, 2),
 datetime.date(2014, 5, 9),
 datetime.date(2014, 5, 16),
 datetime.date(2014, 5, 23),
 datetime.date(2014, 5, 30),
 datetime.date(2014, 6, 6),
 datetime.date(2014, 6, 13),
 datetime.date(2014, 6, 20),
 datetime.date(2014, 7, 11),
 datetime.date(2014, 7, 18),
 datetime.date(2014, 7, 25),
 datetime.date(2014, 8, 8),
 datetime.date(2014, 8, 15),
 datetime.date(2014, 8, 22),
 datetime.date(2014, 8, 29),
 datetime.date(2014, 9, 5),
 datetime.date(2014, 9, 12),
 datetime.date(2014, 9, 19),
 datetime.date(2014, 10, 3),
 datetime.date(2014, 10, 10),
 datetime.date(2014, 10, 17),
 datetime.date(2014, 10, 31),
 datetime.date(2014, 11, 7),
 datetime.date(2014, 11, 14),
 datetime.date(2014, 11, 21),
 datetime.date(2015, 2, 27),
 datetime.date(2015, 3, 6),
 datetime.date(2015, 3, 13),
 datetime.date(2015, 4, 10),
 datetime.date(2015, 5, 1),
 datetime.date(2015, 5, 8),
 datetime.date(2015, 5, 22),
 datetime.date(2015, 5, 29),
 datetime.date(2015, 6, 12),
 datetime.date(2015, 6, 19),
 datetime.date(2015, 7, 10),
 datetime.date(2015, 8, 7),
 datetime.date(2015, 8, 14),
 datetime.date(2015, 8, 21),
 datetime.date(2015, 9, 4),
 datetime.date(2015, 9, 11),
 datetime.date(2015, 9, 18),
 datetime.date(2015, 9, 25),
 datetime.date(2015, 10, 9),
 datetime.date(2015, 10, 23),
 datetime.date(2015, 11, 6),
 datetime.date(2015, 11, 13),
 datetime.date(2015, 11, 20),
 datetime.date(2015, 12, 18),
 datetime.date(2016, 1, 8),
 datetime.date(2016, 1, 15),
 datetime.date(2016, 1, 22),
 datetime.date(2016, 1, 29),
 datetime.date(2016, 2, 5),
 datetime.date(2016, 2, 19),
 datetime.date(2016, 2, 26),
 datetime.date(2016, 3, 4),
 datetime.date(2016, 3, 11),
 datetime.date(2016, 3, 18),
 datetime.date(2016, 3, 25),
 datetime.date(2016, 4, 1),
 datetime.date(2016, 4, 8),
 datetime.date(2016, 4, 22),
 datetime.date(2016, 4, 29),
 datetime.date(2016, 5, 6),
 datetime.date(2016, 5, 13),
 datetime.date(2016, 5, 20),
 datetime.date(2016, 5, 27),
 datetime.date(2016, 6, 3),
 datetime.date(2016, 6, 17),
 datetime.date(2016, 6, 24),
 datetime.date(2016, 7, 1),
 datetime.date(2016, 7, 8),
 datetime.date(2016, 7, 15),
 datetime.date(2016, 7, 22),
 datetime.date(2016, 7, 29),
 datetime.date(2016, 8, 5),
 datetime.date(2016, 8, 19),
 datetime.date(2016, 8, 26),
 datetime.date(2016, 9, 2),
 datetime.date(2016, 9, 9),
 datetime.date(2016, 9, 16),
 datetime.date(2016, 9, 23),
 datetime.date(2016, 9, 30),
 datetime.date(2016, 10, 7),
 datetime.date(2016, 10, 14),
 datetime.date(2016, 10, 21),
 datetime.date(2016, 10, 28),
 datetime.date(2016, 11, 4),
 datetime.date(2016, 11, 11),
 datetime.date(2016, 11, 18),
 datetime.date(2016, 11, 25),
 datetime.date(2016, 12, 2),
 datetime.date(2016, 12, 16),
 datetime.date(2016, 12, 23),
 datetime.date(2016, 12, 30),
 datetime.date(2017, 1, 6),
 datetime.date(2017, 1, 13),
 datetime.date(2017, 1, 20),
 datetime.date(2017, 1, 27),
 datetime.date(2017, 2, 3),
 datetime.date(2017, 2, 10),
 datetime.date(2017, 2, 17),
 datetime.date(2017, 2, 24),
 datetime.date(2017, 3, 3),
 datetime.date(2017, 3, 10),
 datetime.date(2017, 3, 24),
 datetime.date(2017, 3, 31),
 datetime.date(2017, 4, 7),
 datetime.date(2017, 4, 14),
 datetime.date(2017, 4, 21),
 datetime.date(2017, 4, 28),
 datetime.date(2017, 5, 5),
 datetime.date(2017, 5, 12),
 datetime.date(2017, 5, 19),
 datetime.date(2017, 5, 26),
 datetime.date(2017, 6, 2),
 datetime.date(2017, 6, 9),
 datetime.date(2017, 6, 16),
 datetime.date(2017, 6, 30),
 datetime.date(2017, 7, 7),
 datetime.date(2017, 7, 21),
 datetime.date(2017, 7, 28),
 datetime.date(2017, 8, 11),
 datetime.date(2017, 8, 18),
 datetime.date(2017, 8, 25),
 datetime.date(2017, 9, 1),
 datetime.date(2017, 9, 8),
 datetime.date(2017, 9, 15),
 datetime.date(2017, 9, 22),
 datetime.date(2017, 9, 29),
 datetime.date(2017, 10, 6),
 datetime.date(2017, 10, 20),
 datetime.date(2017, 10, 27),
 datetime.date(2017, 11, 3),
 datetime.date(2017, 11, 10),
 datetime.date(2017, 11, 17),
 datetime.date(2017, 11, 24),
 datetime.date(2017, 12, 1),
 datetime.date(2017, 12, 8),
 datetime.date(2017, 12, 15),
 datetime.date(2017, 12, 22),
 datetime.date(2018, 1, 12),
 datetime.date(2018, 1, 26),
 datetime.date(2018, 2, 2),
 datetime.date(2018, 2, 9),
 datetime.date(2018, 2, 16),
 datetime.date(2018, 2, 23),
 datetime.date(2018, 3, 9),
 datetime.date(2018, 3, 16),
 datetime.date(2018, 3, 23),
 datetime.date(2018, 4, 6),
 datetime.date(2018, 4, 13),
 datetime.date(2018, 4, 20),
 datetime.date(2018, 4, 27),
 datetime.date(2018, 5, 11),
 datetime.date(2018, 5, 18),
 datetime.date(2018, 6, 1),
 datetime.date(2018, 6, 8),
 datetime.date(2018, 6, 22),
 datetime.date(2018, 6, 29),
 datetime.date(2018, 7, 6),
 datetime.date(2018, 7, 13),
 datetime.date(2018, 7, 20),
 datetime.date(2018, 7, 27),
 datetime.date(2018, 8, 10),
 datetime.date(2018, 8, 17),
 datetime.date(2018, 8, 24),
 datetime.date(2018, 9, 7),
 datetime.date(2018, 9, 14),
 datetime.date(2018, 10, 5),
 datetime.date(2018, 10, 26),
 datetime.date(2018, 11, 2),
 datetime.date(2018, 11, 9),
 datetime.date(2018, 11, 16),
 datetime.date(2018, 11, 23),
 datetime.date(2018, 11, 30),
 datetime.date(2018, 12, 14),
 datetime.date(2018, 12, 21),
 datetime.date(2018, 12, 28),
 datetime.date(2019, 1, 4),
 datetime.date(2019, 1, 11),
 datetime.date(2019, 1, 18),
 datetime.date(2019, 1, 25),
 datetime.date(2019, 2, 1),
 datetime.date(2019, 2, 8),
 datetime.date(2019, 2, 15),
 datetime.date(2019, 3, 8),
 datetime.date(2019, 3, 15),
 datetime.date(2019, 3, 22),
 datetime.date(2019, 3, 29),
 datetime.date(2019, 4, 5),
 datetime.date(2019, 4, 12),
 datetime.date(2019, 4, 26),
 datetime.date(2019, 5, 3),
 datetime.date(2019, 5, 10),
 datetime.date(2019, 5, 17),
 datetime.date(2019, 5, 24),
 datetime.date(2019, 5, 31),
 datetime.date(2019, 6, 14),
 datetime.date(2019, 6, 28),
 datetime.date(2019, 7, 5),
 datetime.date(2019, 7, 12),
 datetime.date(2019, 7, 19),
 datetime.date(2019, 8, 2),
 datetime.date(2019, 8, 9),
 datetime.date(2019, 8, 16),
 datetime.date(2019, 8, 23),
 datetime.date(2019, 8, 30),
 datetime.date(2019, 9, 6),
 datetime.date(2019, 9, 13),
 datetime.date(2019, 10, 4),
 datetime.date(2019, 10, 11),
 datetime.date(2019, 10, 18),
 datetime.date(2019, 10, 25),
 datetime.date(2019, 11, 1),
 datetime.date(2019, 11, 8),
 datetime.date(2019, 11, 15),
 datetime.date(2019, 11, 22),
 datetime.date(2019, 11, 29),
 datetime.date(2019, 12, 6),
 datetime.date(2019, 12, 13),
 datetime.date(2019, 12, 20),
 datetime.date(2019, 12, 27),
 datetime.date(2020, 1, 3),
 datetime.date(2020, 1, 10),
 datetime.date(2020, 1, 17),
 datetime.date(2020, 1, 24),
 datetime.date(2020, 1, 31),
 datetime.date(2020, 2, 7),
 datetime.date(2020, 2, 14),
 datetime.date(2020, 2, 21),
 datetime.date(2020, 2, 28),
 datetime.date(2020, 3, 6),
 datetime.date(2020, 3, 13),
 datetime.date(2020, 3, 20),
 datetime.date(2020, 3, 27),
 datetime.date(2020, 4, 3),
 datetime.date(2020, 4, 10),
 datetime.date(2020, 4, 17),
 datetime.date(2020, 4, 24),
 datetime.date(2020, 5, 1),
 datetime.date(2020, 5, 8),
 datetime.date(2020, 5, 15),
 datetime.date(2020, 5, 22),
 datetime.date(2020, 6, 5),
 datetime.date(2020, 6, 12),
 datetime.date(2020, 6, 19),
 datetime.date(2020, 6, 26),
 datetime.date(2020, 7, 3),
 datetime.date(2020, 7, 10),
 datetime.date(2020, 7, 17),
 datetime.date(2020, 7, 24),
 datetime.date(2020, 8, 7),
 datetime.date(2020, 8, 14),
 datetime.date(2020, 8, 21),
 datetime.date(2020, 8, 28),
 datetime.date(2020, 9, 4),
 datetime.date(2020, 9, 11),
 datetime.date(2020, 9, 25),
 datetime.date(2020, 10, 2),
 datetime.date(2020, 10, 16),
 datetime.date(2020, 10, 23),
 datetime.date(2021, 6, 18),
 datetime.date(2021, 7, 2),
 datetime.date(2021, 7, 9),
 datetime.date(2021, 7, 16),
 datetime.date(2021, 7, 30),
 datetime.date(2021, 8, 6),
 datetime.date(2021, 8, 13),
 datetime.date(2021, 8, 20),
 datetime.date(2021, 9, 3),
 datetime.date(2021, 9, 10),
 datetime.date(2021, 9, 17),
 datetime.date(2021, 9, 24),
 datetime.date(2021, 10, 1),
 datetime.date(2021, 10, 8),
 datetime.date(2021, 10, 15),
 datetime.date(2021, 10, 22),
 datetime.date(2021, 10, 29),
 datetime.date(2021, 11, 5),
 datetime.date(2021, 11, 26),
 datetime.date(2021, 12, 3),
 datetime.date(2021, 12, 10),
 datetime.date(2021, 12, 17),
 datetime.date(2021, 12, 24),
 datetime.date(2022, 1, 7),
 datetime.date(2022, 1, 14),
 datetime.date(2022, 1, 21),
 datetime.date(2022, 1, 28),
 datetime.date(2022, 2, 4),
 datetime.date(2022, 2, 11),
 datetime.date(2022, 2, 18),
 datetime.date(2022, 2, 25),
 datetime.date(2022, 3, 4),
 datetime.date(2022, 3, 11),
 datetime.date(2022, 3, 18),
 datetime.date(2022, 3, 25),
 datetime.date(2022, 4, 1),
 datetime.date(2022, 4, 8),
 datetime.date(2022, 4, 22),
 datetime.date(2022, 4, 29),
 datetime.date(2022, 5, 6),
 datetime.date(2022, 5, 13),
 datetime.date(2022, 5, 20),
 datetime.date(2022, 5, 27),
 datetime.date(2022, 6, 3),
 datetime.date(2022, 6, 10),
 datetime.date(2022, 6, 17),
 datetime.date(2022, 6, 24),
 datetime.date(2022, 7, 8),
 datetime.date(2022, 7, 15),
 datetime.date(2022, 8, 5),
 datetime.date(2022, 8, 12),
 datetime.date(2022, 8, 19),
 datetime.date(2022, 8, 26),
 datetime.date(2022, 9, 2),
 datetime.date(2022, 9, 9),
 datetime.date(2022, 9, 16),
 datetime.date(2022, 9, 23),
 datetime.date(2022, 9, 30),
 datetime.date(2022, 10, 7),
 datetime.date(2022, 10, 14),
 datetime.date(2022, 10, 21),
 datetime.date(2022, 10, 28),
 datetime.date(2022, 11, 11),
 datetime.date(2022, 11, 18),
 datetime.date(2022, 11, 25),
 datetime.date(2022, 12, 2),
 datetime.date(2022, 12, 9),
 datetime.date(2022, 12, 16),
 datetime.date(2022, 12, 23),
 datetime.date(2023, 1, 20),
 datetime.date(2023, 1, 27),
 datetime.date(2023, 2, 3),
 datetime.date(2023, 2, 10),
 datetime.date(2023, 3, 3),
 datetime.date(2023, 3, 10),
 datetime.date(2023, 3, 17),
 datetime.date(2023, 3, 24),
 datetime.date(2023, 3, 31),
 datetime.date(2023, 4, 7),
 datetime.date(2023, 4, 14),
 datetime.date(2023, 4, 21),
 datetime.date(2023, 4, 28),
 datetime.date(2023, 5, 5),
 datetime.date(2023, 5, 12),
 datetime.date(2023, 5, 19),
 datetime.date(2023, 5, 26),
 datetime.date(2023, 6, 2),
 datetime.date(2023, 6, 9),
 datetime.date(2023, 6, 16),
 datetime.date(2023, 6, 23),
 datetime.date(2023, 7, 7),
 datetime.date(2023, 7, 14),
 datetime.date(2023, 7, 21),
 datetime.date(2023, 7, 28),
 datetime.date(2023, 8, 4),
 datetime.date(2023, 8, 11),
 datetime.date(2023, 8, 18),
 datetime.date(2023, 8, 25),
 datetime.date(2023, 9, 1),
 datetime.date(2023, 9, 8),
 datetime.date(2023, 9, 15),
 datetime.date(2023, 9, 22),
 datetime.date(2023, 9, 29),
 datetime.date(2023, 10, 6),
 datetime.date(2023, 10, 13),
 datetime.date(2023, 10, 20),
 datetime.date(2023, 10, 27),
 datetime.date(2023, 11, 3),
 datetime.date(2023, 11, 10),
 datetime.date(2023, 11, 17),
 datetime.date(2023, 11, 24),
 datetime.date(2023, 12, 1),
 datetime.date(2023, 12, 8),
 datetime.date(2023, 12, 15),
 datetime.date(2024, 1, 12),
 datetime.date(2024, 1, 26),
 datetime.date(2024, 2, 2),
 datetime.date(2024, 2, 9),
 datetime.date(2024, 2, 16),
 datetime.date(2024, 2, 23),
 datetime.date(2024, 3, 1),
 datetime.date(2024, 3, 8),
 datetime.date(2024, 3, 15),
 datetime.date(2024, 3, 22),
 datetime.date(2024, 4, 5),
 datetime.date(2024, 4, 12),
 datetime.date(2024, 4, 19),
 datetime.date(2024, 4, 26),
 datetime.date(2024, 5, 3),
 datetime.date(2024, 5, 10),
 datetime.date(2024, 5, 17),
 datetime.date(2024, 5, 24),
 datetime.date(2024, 5, 31),
 datetime.date(2024, 6, 7),
 datetime.date(2024, 6, 21),
 datetime.date(2024, 6, 28),
 datetime.date(2024, 6, 29),
 datetime.date(2024, 7, 5),
 datetime.date(2024, 7, 12),
 datetime.date(2024, 7, 19),
 datetime.date(2024, 7, 26),
 datetime.date(2024, 8, 2),
 datetime.date(2024, 8, 9),
 datetime.date(2024, 8, 16),
 datetime.date(2024, 8, 23),
 datetime.date(2024, 8, 30),
 datetime.date(2024, 9, 6),
 datetime.date(2024, 9, 13),
 datetime.date(2024, 9, 14),
 datetime.date(2024, 9, 20),
 datetime.date(2024, 9, 27),
 datetime.date(2024, 10, 4),
 datetime.date(2024, 10, 11),
 datetime.date(2024, 10, 18),
 datetime.date(2024, 10, 25),
 datetime.date(2024, 11, 8),
 datetime.date(2024, 11, 15),
 datetime.date(2024, 11, 22),
 datetime.date(2024, 11, 29),
 datetime.date(2024, 12, 6),
 datetime.date(2024, 12, 13),
 datetime.date(2024, 12, 20),
 datetime.date(2024, 12, 27),
 datetime.date(2025, 1, 3),
 datetime.date(2025, 1, 10),
 datetime.date(2025, 1, 17),
 datetime.date(2025, 1, 24),
 datetime.date(2025, 1, 31),
 datetime.date(2025, 2, 7),
 datetime.date(2025, 2, 21),
 datetime.date(2025, 2, 28),
 datetime.date(2025, 3, 7),
 datetime.date(2025, 3, 14),
 datetime.date(2025, 3, 21),
 datetime.date(2025, 3, 28),
 datetime.date(2025, 4, 4),
 datetime.date(2025, 4, 11),
 datetime.date(2025, 4, 25),
 datetime.date(2025, 5, 2),
 datetime.date(2025, 5, 9),
 datetime.date(2025, 5, 16),
 datetime.date(2025, 5, 23),
 datetime.date(2025, 5, 30),
 datetime.date(2025, 6, 6),
 datetime.date(2025, 6, 20),
 datetime.date(2025, 7, 11),
 datetime.date(2025, 7, 18),
 datetime.date(2025, 7, 25),
 datetime.date(2025, 8, 8),
 datetime.date(2025, 8, 22),
 datetime.date(2025, 8, 29),
 datetime.date(2025, 9, 5),
 datetime.date(2025, 9, 12),
 datetime.date(2025, 9, 13),
 datetime.date(2025, 9, 19),
 datetime.date(2025, 9, 26),
 datetime.date(2025, 10, 3),
 datetime.date(2025, 10, 10),
 datetime.date(2025, 10, 17),
 datetime.date(2025, 10, 24),
 datetime.date(2025, 10, 31),
 datetime.date(2025, 11, 7),
 datetime.date(2025, 11, 14),
 datetime.date(2025, 11, 21),
 datetime.date(2025, 11, 28),
 datetime.date(2025, 12, 12),
 datetime.date(2025, 12, 19),
 datetime.date(2026, 1, 16),
 datetime.date(2026, 1, 23),
 datetime.date(2026, 1, 30),
 datetime.date(2026, 2, 6),
 datetime.date(2026, 2, 13),
 datetime.date(2026, 2, 27),
 datetime.date(2026, 3, 6),
 datetime.date(2026, 3, 13),
 datetime.date(2026, 3, 20),
 datetime.date(2026, 3, 27),
 datetime.date(2026, 4, 10),
 datetime.date(2026, 4, 17),
 datetime.date(2026, 5, 1),
 datetime.date(2026, 5, 8),
 datetime.date(2026, 5, 15),
 datetime.date(2026, 5, 22),
 datetime.date(2026, 5, 29),
 datetime.date(2026, 6, 12),
 datetime.date(2026, 6, 19),
 datetime.date(2026, 6, 26),
 datetime.date(2026, 7, 3),
 datetime.date(2026, 7, 10),
 datetime.date(2026, 7, 17),
 datetime.date(2026, 7, 24)]

In [391]:
votes

,filled_by,date,category,winner,in_pub,points,winner_num
3866,Scott,2014-01-03,Goal of the Night,Paul L,True,1,1
3867,Scott,2014-01-03,Save of the Night,John B,False,0,1
3856,Scott,2014-01-10,Captains Performance,John B,True,1,1
3858,Scott,2014-01-10,Duffer,Didier C,True,-1,1
3859,Scott,2014-01-10,Duffer,Mark L,True,-1,2
...,...,...,...,...,...,...,...
412,Andrew,2026-07-24,Golden Goal,Tilo,False,0,1
411,Andrew,2026-07-24,Greedy Bastard,Stevie,False,-2,1
406,Andrew,2026-07-24,Save of the Night,Hubert,True,1,1
407,Andrew,2026-07-24,Skill Moment,Neil H,False,0,1
408,Andrew,2026-07-24,Worst Tackle,Gio,True,1,1

In [388]:
votes["category"] = votes["category"].replace("Captain's Performance", "Captains Performance")

In [392]:
votes.to_csv(f"baarbierians_voting_backup_{date.today().isoformat()}.csv", index=False)